"""initial schema

Revision ID: 30ea213684d2
Revises: 
Create Date: 2026-08-27 18:33:11.201138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30ea213684d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('customer', 'vendor', name='entity_type_enum'), nullable=False),
    sa.Column('entity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_tenant_id'), 'entities', ['tenant_id'], unique=False)
    op.create_table('ingestion_batches',
    sa.Column('source_type', sa.Enum('ledger', 'bank', 'gateway', 'master', name='source_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ingesting', 'normalizing', 'matching', 'ai_resolving', 'completed', 'failed', name='batch_status_enum'), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_batches_tenant_id'), 'ingestion_batches', ['tenant_id'], unique=False)
    op.create_table('match_audit_log',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.Enum('system', 'ai', 'user', name='audit_actor_enum'), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_audit_log_subject_id'), 'match_audit_log', ['subject_id'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('alias_text', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_aliases_alias_text'), 'entity_aliases', ['alias_text'], unique=False)
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_table('raw_records',
    sa.Column('source_type', sa.Enum('ledger', 'bank', 'gateway', 'master', name='source_type_enum'), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_records_batch_id'), 'raw_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_raw_records_tenant_id'), 'raw_records', ['tenant_id'], unique=False)
    op.create_table('normalized_records',
    sa.Column('source_type', sa.Enum('ledger', 'bank', 'gateway', 'master', name='source_type_enum'), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('txn_id', sa.String(), nullable=True),
    sa.Column('reference_no', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('narration_raw', sa.String(), nullable=True),
    sa.Column('narration_clean', sa.String(), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('unmatched', 'matched', 'ai_suggested', 'exception', name='record_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['raw_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_records_batch_id'), 'normalized_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_normalized_records_reference_no'), 'normalized_records', ['reference_no'], unique=False)
    op.create_index(op.f('ix_normalized_records_source_record_id'), 'normalized_records', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_normalized_records_tenant_id'), 'normalized_records', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_normalized_records_txn_id'), 'normalized_records', ['txn_id'], unique=False)
    op.create_table('matches',
    sa.Column('ledger_record_id', sa.UUID(), nullable=True),
    sa.Column('bank_record_id', sa.UUID(), nullable=True),
    sa.Column('gateway_record_id', sa.UUID(), nullable=True),
    sa.Column('match_type', sa.Enum('exact', 'reference', 'amount_tolerance', 'date_window', 'one_to_many', 'ai_suggested', name='match_type_enum'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('matched_by', sa.Enum('rule', 'ai', 'human', name='matched_by_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_record_id'], ['normalized_records.id'], ),
    sa.ForeignKeyConstraint(['gateway_record_id'], ['normalized_records.id'], ),
    sa.ForeignKeyConstraint(['ledger_record_id'], ['normalized_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_tenant_id'), 'matches', ['tenant_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('ai_suggested_match_id', sa.UUID(), nullable=True),
    sa.Column('confidence_tier', sa.Enum('low', 'medium', 'high', name='confidence_tier_enum'), nullable=True),
    sa.Column('reason_code', sa.Enum('AMT_MISMATCH', 'FEE_DEDUCTED', 'MISSING_REFERENCE', 'SPLIT_PAYMENT', 'DUPLICATE', 'UNKNOWN_COUNTERPARTY', name='reason_code_enum'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('open', 'approved', 'rejected', 'edited', 'resolved', name='exception_status_enum'), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_suggested_match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['normalized_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_record_id'), 'exceptions', ['record_id'], unique=False)
    op.create_index(op.f('ix_exceptions_tenant_id'), 'exceptions', ['tenant_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('exception_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_tenant_id'), 'llm_calls', ['tenant_id'], unique=False)
    op.create_table('matching_rules',
    sa.Column('rule_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_from_exception_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_from_exception_id'], ['exceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_rules_tenant_id'), 'matching_rules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matching_rules_tenant_id'), table_name='matching_rules')
    op.drop_table('matching_rules')
    op.drop_index(op.f('ix_llm_calls_tenant_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_exceptions_tenant_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_record_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_matches_tenant_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_normalized_records_txn_id'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_tenant_id'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_source_record_id'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_reference_no'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_batch_id'), table_name='normalized_records')
    op.drop_table('normalized_records')
    op.drop_index(op.f('ix_raw_records_tenant_id'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_batch_id'), table_name='raw_records')
    op.drop_table('raw_records')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_alias_text'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_match_audit_log_subject_id'), table_name='match_audit_log')
    op.drop_table('match_audit_log')
    op.drop_index(op.f('ix_ingestion_batches_tenant_id'), table_name='ingestion_batches')
    op.drop_table('ingestion_batches')
    op.drop_index(op.f('ix_entities_tenant_id'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
