"""fee rules, manual match type

Revision ID: e8c6bb1d3cc5
Revises: 30ea213684d2
Create Date: 2026-08-27 19:14:58.962900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8c6bb1d3cc5'
down_revision: Union[str, None] = '30ea213684d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Postgres enum value additions aren't autodetected by alembic; added by hand.
    op.execute("ALTER TYPE match_type_enum ADD VALUE IF NOT EXISTS 'manual'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_rules',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rule_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_rules_tenant_id'), 'fee_rules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_rules_tenant_id'), table_name='fee_rules')
    op.drop_table('fee_rules')
    # ### end Alembic commands ###
